In [6]:
import pandas as pd

df = pd.read_csv('./qm9.csv')
print(df.columns)
print(df.head())

Index(['mol_id', 'smiles', 'A', 'B', 'C', 'mu', 'alpha', 'homo', 'lumo', 'gap',
       'r2', 'zpve', 'u0', 'u298', 'h298', 'g298', 'cv', 'u0_atom',
       'u298_atom', 'h298_atom', 'g298_atom'],
      dtype='object')
  mol_id smiles          A           B           C      mu  alpha    homo  \
0  gdb_1      C  157.71180  157.709970  157.706990  0.0000  13.21 -0.3877   
1  gdb_2      N  293.60975  293.541110  191.393970  1.6256   9.46 -0.2570   
2  gdb_3      O  799.58812  437.903860  282.945450  1.8511   6.31 -0.2928   
3  gdb_4    C#C    0.00000   35.610036   35.610036  0.0000  16.28 -0.2845   
4  gdb_5    C#N    0.00000   44.593883   44.593883  2.8937  12.99 -0.3604   

     lumo     gap  ...      zpve         u0       u298       h298       g298  \
0  0.1171  0.5048  ...  0.044749 -40.478930 -40.476062 -40.475117 -40.498597   
1  0.0829  0.3399  ...  0.034358 -56.525887 -56.523026 -56.522082 -56.544961   
2  0.0687  0.3615  ...  0.021375 -76.404702 -76.401867 -76.400922 -76.422349   


In [19]:
import numpy as np
qm9_3d = np.load('./qm9_eV.npz', allow_pickle=True)
print(len(qm9_3d['mu']))


lst = qm9_3d.files

for item in lst[10:20]:
    print(item)
    print(qm9_3d[item])

130831
lumo
[3.1864533  2.2558239  1.86942222 ... 1.95921979 2.39732311 2.01908484]
gap
[13.73630767  9.24915011  9.83691605 ...  8.03552229  8.17157922
  8.32124185]
r2
[ 35.3641  26.1563  19.0002 ... 780.3553 803.1904 756.3557]
zpve
[1.21768231 0.9349288  0.58164338 ... 3.82205686 4.1421716  3.47930224]
U0
[-17.17218053 -12.00585399  -9.24036083 ... -72.2899858  -77.82129866
 -69.53317307]
U
[-17.2868221  -12.08212751  -9.27881052 ... -72.80101563 -78.36813868
 -70.00945396]
H
[-17.38965393 -12.15927179  -9.33021283 ... -73.2122341  -78.8050719
 -70.39495767]
G
[-16.15191683 -11.24600325  -8.73384809 ... -67.17726569 -72.43328096
 -64.71000932]
Cv
[ 6.469  6.316  6.002 ... 23.972 24.796 23.434]
meta
{'mean': {'A': 0, 'B': 0, 'C': 0, 'mu': 0, 'alpha': 0, 'homo': 0, 'lumo': 0, 'gap': 0, 'r2': 0, 'zpve': 0, 'U0': 0, 'U': 0, 'H': 0, 'G': 0, 'Cv': 0}, 'std': {'A': 1, 'B': 1, 'C': 1, 'mu': 1, 'alpha': 1, 'homo': 0.03674932247495664, 'lumo': 0.03674932247495664, 'gap': 0.03674932247495664, 